linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gocritic
    - gofmt
    - goimports
    - misspell

linters-settings:
  gocritic:
    disabled-checks:
      - fieldalignment
      - hugeParam

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: cmd/test/
      linters:
        - errcheck
